FROM openjdk:8-jre-alpine

################################
# load spring application source
################################
# git에서 코드 끌어오고

# gradle 빌드하고

# entrypoint 옮기고
ADD /scripts /bin/

# jar 싸악 실행
ENTRYPOINT ["/bin/entrypoint.sh"]